### ISSUE TITLE
Question about decision column in Invite and Request tables 

### ISSUE THREAD

**Issue by taiyrbegeyev** [techclubjacobs/server#3]
[https://github.com/techclubjacobs/app/wiki/Database](url)

### **Invite** Table
| Field       | Type     |
| ----------- | --------- |
| invite_id  | int(11)  |
| user_id   | int(11)  |
| message| varchar(160) |
| decision  | varchar(160) |

### **Request Table**
| Field       | Type     |
| ----------- | --------- |
| request_id  | int(11)  |
| user_id   | int(11)  |
| message| varchar(160) |
| decision  | int(11) |

Why do **_decision_** columns have different data types?

**Comment by stevenabreu7** [comment]
I have no idea to be honest haha

**Comment by stevenabreu7** [comment]
@mgranderath what do you think? I think it was in your db schema, what is the decision field?

**Comment by mgranderath** [comment]
I remember it as being a field which can have 4 states. 

- Nothing
- Accepted
- Rejected
- Interested

So I guess an *int* makes more sense as a enum
